# Generated by Django 5.0.4 on 2024-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passportApplication', '0007_alter_pasapp_passport_scan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasapp',
            name='recipient',
        ),
        migrations.AddField(
            model_name='pasapp',
            name='birth_scan',
            field=models.ImageField(default=None, null=True, upload_to='birth_scans/', verbose_name='Скан свидетельства'),
        ),
        migrations.AddField(
            model_name='pasapp',
            name='cause',
            field=models.CharField(choices=[('возраст', 'Достижение 20 или 45 лет'), ('фио', 'Изменение фамилии,имени или отчества'), ('обстоятельства', 'Потеря или непригодность к использованию'), ('ошибка', 'Ошибка в паспорте'), ('внешность', 'Изменение внешности')], default='Достижение 20 или 45 лет', max_length=50, verbose_name='причина'),
        ),
        migrations.AddField(
            model_name='pasapp',
            name='marriage_scan',
            field=models.ImageField(default=None, null=True, upload_to='marriage_scans/', verbose_name='Скан брака'),
        ),
        migrations.AlterField(
            model_name='pasapp',
            name='application_type',
            field=models.CharField(choices=[('получение', 'Получение паспорта'), ('замена', 'Замена паспорта')], max_length=50),
        ),
    ]
