# Generated by Django 5.0.4 on 2024-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passportApplication', '0008_remove_pasapp_recipient_pasapp_birth_scan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasapp',
            name='reason',
        ),
    ]
