# Generated by Django 5.0.6 on 2024-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passportApplication', '0009_remove_pasapp_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasapp',
            name='application_type',
            field=models.CharField(choices=[('получение', 'Получение паспорта'), ('замена', 'Замена паспорта')], default='Получение паспорта', max_length=50),
        ),
    ]
