# Generated by Django 5.0.6 on 2024-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('hospital', '0002_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', to='doctor.doctor', verbose_name='Врачи'),
        ),
    ]
