# Generated by Django 5.0.6 on 2024-05-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
    ]
