# Generated by Django 5.0.6 on 2024-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_hospital'),
        ('hospital', '0004_remove_hospital_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', to='doctor.doctor', verbose_name='Врачи'),
        ),
    ]
