# Generated by Django 5.0.6 on 2024-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_options_remove_doctor_first_name_and_more'),
        ('hospital', '0005_hospital_doctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registry_number',
            field=models.CharField(max_length=50),
        ),
    ]
