# Generated by Django 5.0.6 on 2024-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_options_remove_doctor_first_name_and_more'),
        ('hospital', '0006_alter_hospital_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', to='doctor.doctor'),
        ),
    ]
