# Generated by Django 5.0.6 on 2024-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
