# Generated by Django 5.0.6 on 2024-05-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, verbose_name='Номер полиса')),
                ('expiry_date', models.DateField(verbose_name='Срок действия')),
                ('insurer_id', models.CharField(max_length=50, verbose_name='Идентификатор страховой')),
                ('insurer_name', models.CharField(max_length=100, verbose_name='Название страховой')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Где выдан')),
            ],
        ),
    ]
