# Generated by Django 5.0.6 on 2024-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insapp',
            name='passport_scan',
            field=models.ImageField(default=None, upload_to='passport_scans/', verbose_name='Скан паспорта'),
        ),
        migrations.AddField(
            model_name='insapp',
            name='recipient',
            field=models.CharField(choices=[('себе', 'Себе'), ('ребенку', 'Ребенку')], default='Себе', max_length=50, verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='insapp',
            name='signature_scan',
            field=models.ImageField(default=None, upload_to='signature_scans/', verbose_name='Скан подписи'),
        ),
        migrations.AddField(
            model_name='insapp',
            name='status',
            field=models.CharField(choices=[('ожидание', 'Ожидание'), ('подтверждено', 'Подтверждено'), ('отменено', 'Отменено')], default='ожидание', max_length=15, verbose_name='Статус'),
        ),
    ]
