# Generated by Django 5.0.6 on 2024-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApplication', '0005_alter_insapp_passport_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insapp',
            name='passport_scan',
            field=models.ImageField(upload_to='passport_scans/', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='insapp',
            name='signature_scan',
            field=models.ImageField(upload_to='signature_scans/', verbose_name='Скан подписи'),
        ),
    ]
