# Generated by Django 5.0.6 on 2024-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceApplication', '0009_alter_insapp_passport_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insapp',
            name='passport_scan',
            field=models.ImageField(default=None, null=True, upload_to='passport_scans/', verbose_name='Скан паспорта'),
        ),
    ]
