# Generated by Django 5.0.6 on 2024-06-06 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaсReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('vaccine_type', models.CharField(choices=[('covid', 'COVID-19'), ('flu', 'Грипп'), ('hep_b', 'Гепатит B')], max_length=10, verbose_name='Тип вакцины')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('ожидание', 'Ожидание'), ('одобрено', 'Одобрено'), ('отклонено', 'Отклонено')], default='ожидание', max_length=10, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на прививку',
                'verbose_name_plural': 'Заявки на прививки',
            },
        ),
    ]
