# Generated by Django 5.0.6 on 2024-06-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaсreq',
            name='patient_name',
        ),
    ]
