# Generated by Django 5.0.6 on 2024-06-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_insurance', '0002_medinsurance_user'),
        ('vaccinationApplication', '0002_remove_vaсreq_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaсreq',
            name='age',
        ),
        migrations.AddField(
            model_name='vaсreq',
            name='insurance_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_vaccination', to='med_insurance.medinsurance'),
        ),
    ]
