# Generated by Django 5.0.6 on 2024-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0004_alter_vaсreq_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='vaccine_type',
            field=models.CharField(choices=[('covid', 'COVID-19'), ('flu', 'Грипп'), ('hep_b', 'Гепатит B')], default='COVID-19', max_length=10, verbose_name='Тип вакцины'),
        ),
    ]
