# Generated by Django 5.0.6 on 2024-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0005_alter_vaсreq_vaccine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaсreq',
            name='point',
            field=models.CharField(default=None, max_length=100, verbose_name='Пункт вакцинации'),
        ),
        migrations.AddField(
            model_name='vaсreq',
            name='visit_date',
            field=models.DateField(default=None, verbose_name='Дата вакцинации'),
        ),
    ]
