# Generated by Django 5.0.6 on 2024-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0006_vaсreq_point_vaсreq_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='point',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Пункт вакцинации'),
        ),
        migrations.AlterField(
            model_name='vaсreq',
            name='visit_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата вакцинации'),
        ),
    ]
