# Generated by Django 5.0.6 on 2024-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0008_alter_vaсreq_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='visit_date',
            field=models.DateField(default=None, verbose_name='Дата вакцинации'),
        ),
    ]
