# Generated by Django 5.0.6 on 2024-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0010_alter_vaсreq_point_alter_vaсreq_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='point',
            field=models.CharField(default=None, max_length=100, verbose_name='Пункт вакцинации'),
        ),
    ]
