# Generated by Django 5.0.6 on 2024-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0012_alter_vaсreq_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='point',
            field=models.TextField(default='Москва', max_length=100, verbose_name='Пункт вакцинации'),
        ),
    ]
