# Generated by Django 5.0.6 on 2024-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationApplication', '0015_alter_vaсreq_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaсreq',
            name='point',
            field=models.CharField(default='None', max_length=100, verbose_name='Пункт вакцинации'),
        ),
        migrations.AlterField(
            model_name='vaсreq',
            name='visit_date',
            field=models.DateField(default=None, verbose_name='Дата вакцинации'),
        ),
    ]
