# Generated by Django 5.0.6 on 2024-06-09 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyFarmingSupport', '0002_famfarm_status'),
        ('passport', '0002_passport_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_address',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_city',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_full_name',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_phone',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_website',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='applicant_zip_code',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='city',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_address',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_city',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_email',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_phone',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_website',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='partner_zip_code',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='famfarm',
            name='project_name',
        ),
        migrations.AddField(
            model_name='famfarm',
            name='TIN',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='base_scan',
            field=models.ImageField(default=None, null=True, upload_to='base_scans/', verbose_name='Материально-техническая база'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки на учет'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='experience_scan',
            field=models.ImageField(default=None, null=True, upload_to='experience_scans/', verbose_name='Опыт руководителя'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='passport_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passport_farming', to='passport.passport'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='registration_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='statement_scan',
            field=models.ImageField(default=None, null=True, upload_to='statement_scans/', verbose_name='Финансовая отчетность'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='tax_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Налоговый орган'),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='famfarm',
            name='сharter_scan',
            field=models.ImageField(default=None, null=True, upload_to='сharter_scans/', verbose_name='Устав КФХ'),
        ),
    ]
