# Generated by Django 5.0.6 on 2024-06-09 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyFarmingSupport', '0003_remove_famfarm_applicant_address_and_more'),
        ('passport', '0002_passport_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famfarm',
            name='сharter_scan',
        ),
        migrations.AddField(
            model_name='famfarm',
            name='charter_scan',
            field=models.ImageField(null=True, upload_to='charter_scans/', verbose_name='Устав КФХ'),
        ),
        migrations.AlterField(
            model_name='famfarm',
            name='base_scan',
            field=models.ImageField(null=True, upload_to='base_scans/', verbose_name='Материально-техническая база'),
        ),
        migrations.AlterField(
            model_name='famfarm',
            name='experience_scan',
            field=models.ImageField(null=True, upload_to='experience_scans/', verbose_name='Опыт руководителя'),
        ),
        migrations.AlterField(
            model_name='famfarm',
            name='passport_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_farming', to='passport.passport'),
        ),
        migrations.AlterField(
            model_name='famfarm',
            name='statement_scan',
            field=models.ImageField(null=True, upload_to='statement_scans/', verbose_name='Финансовая отчетность'),
        ),
        migrations.AlterField(
            model_name='famfarm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
