# Generated by Django 5.0.6 on 2024-06-06 10:33

from django.db import migrations, models
import datetime


def convert_year_to_date(apps, schema_editor):
    RealEstate = apps.get_model('realEstateInfo', 'RealEstate')
    for estate in RealEstate.objects.all():
        estate.year_of_completion_temp = datetime.date(estate.year_of_completion, 1, 1)
        estate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateInfo', '0001_initial'),
    ]

    operations = [
        # Шаг 1: Добавление нового временного поля
        migrations.AddField(
            model_name='realestate',
            name='year_of_completion_temp',
            field=models.DateField(null=True),
        ),
        # Шаг 2: Конвертация данных из старого поля в новое
        migrations.RunPython(convert_year_to_date),
        # Шаг 3: Удаление старого поля
        migrations.RemoveField(
            model_name='realestate',
            name='year_of_completion',
        ),
        # Шаг 4: Переименование нового поля в оригинальное имя
        migrations.RenameField(
            model_name='realestate',
            old_name='year_of_completion_temp',
            new_name='year_of_completion',
        ),
    ]
