# Generated by Django 5.0.6 on 2024-06-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_passport_user'),
        ('realEstateInfo', '0002_alter_realestate_year_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='passport_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='realEstateInfo', to='passport.passport'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='status',
            field=models.CharField(choices=[('ожидание', 'Ожидание'), ('подтверждено', 'Подтверждено'), ('отменено', 'Отменено')], default='ожидание', max_length=15, verbose_name='Статус'),
        ),
    ]
