# Generated by Django 5.0.6 on 2024-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstateInfo', '0003_realestate_passport_data_realestate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='year_of_completion',
            field=models.DateField(verbose_name='Год ввода в эксплуатацию'),
        ),
    ]
