# Generated by Django 5.0.6 on 2024-06-06 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_alter_doctor_options_remove_doctor_first_name_and_more'),
        ('hospital', '0007_alter_hospital_doctors'),
        ('med_insurance', '0002_medinsurance_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('status', models.CharField(choices=[('ожидание', 'Ожидание'), ('подтверждено', 'Подтверждено'), ('отменено', 'Отменено')], default='ожидание', max_length=15, verbose_name='Статус')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Врач')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='Больница')),
                ('med_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_insurance.medinsurance', verbose_name='Медицинская страховка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на прием',
                'verbose_name_plural': 'Запросы на прием',
            },
        ),
    ]
