# Generated by Django 5.0.6 on 2024-06-06 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0004_alter_doctor_options_remove_doctor_first_name_and_more'),
        ('hospital', '0007_alter_hospital_doctors'),
        ('med_insurance', '0002_medinsurance_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentRequest',
            new_name='AppReq',
        ),
    ]
